#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
	alias $command="sudo $command"
done
unset command

se() {
	cd ~/.local/bin
	$EDITOR $(fzf)
}

#alias emacs="emacsclient -nw -a 'nvim'"

# Aliases that ensure my home folder is clean:
alias \
  cabal="cabal --config-file=/home/aayush/.local/share/cabal/alias" \
  monerod="monerod --data-dir ${XDG_DATA_HOME}/bitmonero" \
  mbsync="mbsync -c ${XDG_CONFIG_HOME}/mbsync/mbsyncrc"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="yt-dlp -N 10 --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
#
	#ls="ls -hN --color=auto --group-directories-first" \
alias \
  ls="lsd" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="shutdown -h now" \
	e="\$EDITOR" \
	v="\$EDITOR" \
	p="pacman" \
	z="zathura"

alias \
	lf="lfub" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc"
#weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
